use_frameworks!
platform :ios, '8.0'

target 'SPhotoBookKitExample' do
#    pod 'DFARecordKit'
    pod 'Masonry', '1.1.0'
    pod 'Reveal-SDK', '~> 13', :configurations => ['Debug']
    pod 'SPhotoBookKit', :path => '../'

    target 'SPhotoBookKitExampleTests' do
        inherit! :search_paths

    
    end
end
